package input

type ModeKeymap map[string]Action

type Keymap map[InputMode]ModeKeymap

var DefaultKeymap = Keymap{
	ModeInsert: {
		"ctrl+s": ActionSave,
		"ctrl+q": ActionQuit,
		"ctrl+p": ActionPreview,
		"ctrl+h": ActionHelp,
		"esc":    ActionCancel,
		"enter":  ActionConfirm,
	},
	ModeNormal: {
		"ctrl+s":    ActionSave,
		"ctrl+q":    ActionQuit,
		"ctrl+p":    ActionPreview,
		"ctrl+h":    ActionHelp,
		"esc":       ActionCancel,
		"enter":     ActionConfirm,
		"up":        ActionMoveUp,
		"down":      ActionMoveDown,
		"left":      ActionMoveLeft,
		"right":     ActionMoveRight,
		"alt+right": ActionNextWord,
		"alt+left":  ActionPreviousWord,
		"home":      ActionStartOfLine,
		"end":       ActionEndOfLine,
		"ctrl+home": ActionStartOfFile,
		"ctrl+end":  ActionEndOfFile,
	},
}

var VimKeymap = Keymap{
	ModeInsert: {
		"ctrl+s": ActionSave,
		"ctrl+q": ActionQuit,
		"ctrl+p": ActionPreview,
		"esc":    ActionNormalMode,
	},
	ModeNormal: {
		":w":     ActionSave,
		":q":     ActionQuit,
		"ctrl+s": ActionSave,
		"ctrl+q": ActionQuit,
		"ctrl+p": ActionPreview,
		"ctrl+h": ActionHelp,
		"i":      ActionInsertMode,
		"a":      ActionInsertModeNext,
		"o":      ActionInsertModeBelow,
		"O":      ActionInsertModeAbove,
		"h":      ActionMoveLeft,
		"j":      ActionMoveDown,
		"k":      ActionMoveUp,
		"l":      ActionMoveRight,
		"w":      ActionNextWord,
		"b":      ActionPreviousWord,
		"e":      ActionEndOfWord,
		"0":      ActionStartOfLine,
		"$":      ActionEndOfLine,
		"gg":     ActionStartOfFile,
		"G":      ActionEndOfFile,
		"up":     ActionMoveUp,
		"down":   ActionMoveDown,
		"left":   ActionMoveLeft,
		"right":  ActionMoveRight,
	},
	ModeVisual: {
		":w":     ActionSave,
		":q":     ActionQuit,
		"ctrl+s": ActionSave,
		"ctrl+q": ActionQuit,
		"ctrl+p": ActionPreview,
		"ctrl+h": ActionHelp,
		"i":      ActionInsertMode,
		"a":      ActionInsertModeNext,
		"o":      ActionInsertModeBelow,
		"O":      ActionInsertModeAbove,
		"h":      ActionMoveLeft,
		"j":      ActionMoveDown,
		"k":      ActionMoveUp,
		"l":      ActionMoveRight,
		"w":      ActionNextWord,
		"b":      ActionPreviousWord,
		"e":      ActionEndOfWord,
		"0":      ActionStartOfLine,
		"$":      ActionEndOfLine,
		"gg":     ActionStartOfFile,
		"G":      ActionEndOfFile,
		"up":     ActionMoveUp,
		"down":   ActionMoveDown,
		"left":   ActionMoveLeft,
		"right":  ActionMoveRight,
	},
}
